### ISSUE TITLE
Регистрация через Facebook

### ISSUE THREAD

**Issue by akuryachenko** [vkuryachenko/mysite#14]
Организовать регистрацию/логин через Facebook OAuth2

На странице регистрации доступна кнопка
--Или зарегистрироваться через--
`Facebook`

На странице логина есть аналогичная кнопка для логина через FB (что по сути одно и тоже)

Нужно будет зарегистрироваться на FB и создать там приложение типа Web-site и получить нужные ключи.

Попробуй сделать с пом. django-allauth http://django-allauth.readthedocs.org/en/latest/overview.html
Процесс настройки должен быть хорошо задокументирован.

Или http://django-social-auth.readthedocs.org/en/latest/intro.html

**Comment by akuryachenko** [comment]
http://django-social-auth.readthedocs.org/en/latest/backends/facebook.html

**Comment by vkuryachenko** [comment]
DEFAULT_FROM_EMAIL = 'ainf23@rambler.ru'
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(BASE_DIR, 'tmp')

FACEBOOK_APP_ID='511087399095849'
FACEBOOK_API_SECRET='0dadd980719b4c63bba444d5cd1f243c'

**Comment by vkuryachenko** [comment]
http://stackoverflow.com/questions/21295872/facebook-app-localhost-no-longer-works-as-app-domain

**Comment by akuryachenko** [comment]
В общем проблема в кривых ключах, эти кличи неверные, скорее всего из production приложения, у тестового приложения они другие.
После их установки проходит редирект на FB, где можно подтвердить запрос от приложения

**Comment by akuryachenko** [comment]
Замечены следующие проблемы с SOCIALACCOUNT_PROVIDERS = ..
'AUTH_PARAMS': {'auth_type': 'reauthenticate'},  - лучше убрать, тогда пароль лишний раз спрашивать не будут
'VERSION': 'v2.4'  - в настройках самого приложения написана версия 2.5, так что лучше поменять, хотя я не знаю на что это влияет
