### ISSUE TITLE
Добавить requirements.txt

### ISSUE THREAD

**Issue by akuryachenko** [vkuryachenko/mysite#15]
Пропиши все пакеты питоноские, которые нужны для приложения

**Comment by vkuryachenko** [comment]
Django==1.9.4
django-material==0.7.0
django-allauth

**Comment by akuryachenko** [comment]
А где файлик в исходниках проекта?
И не фиксируй версии так строго
Фиксируй мажорную для джанги Django>=1.9,<1.10 и вообще не фиксируй для мелких библиотек

**Comment by vkuryachenko** [comment]
coverage==4.0.3
Django==1.9.4
django-allauth==0.25.2
django-material==0.7.0
django-social-auth==0.7.28
easy-thumbnails==2.3
httplib2==0.9.2
oauth2==1.9.0.post1
oauthlib==1.0.3
Pillow==3.1.1
python-openid==2.2.5
requests==2.9.1
requests-oauthlib==0.6.1
