### ISSUE TITLE
AJAX-based голосование

### ISSUE THREAD

**Issue by akuryachenko** [vkuryachenko/mysite#20]
- Больше на странице голосования нет кнопки "Отправить", 
- теперь голосование происходит при нажатии на вариант ответов.
- после нажатия на вариант показываются результаты голосования в стиле Twitter.

Соответственно переделать DetailView
- Теперь при GET-запросе вид страницы зависит от того голосовал или нет пользователь
- при AJAX POST-запросе возвращается в ответ блок HTML с результатами голосования, который можно подменить на странице.
- ResultView больше не нужна.

По jQuery смотреть $.post, $().serialize, $().replaceWith

**Comment by akuryachenko** [comment]
Если пользователь не залогинен, то после модального окна отправляем аналогичный аяксовый POST-запрос, но возвращаем пустой ответ и редиректим пользователя с пом javascript на страницу регистрации. Редирект в ответ на Ajax запрос браузер не отработает, поэтому эту логику нужно перенести с сервера на клиент

**Comment by vkuryachenko** [comment]
**Больше на странице голосования нет кнопки "Отправить",
    теперь голосование происходит при нажатии на вариант ответов.
    после нажатия на вариант показываются результаты голосования** в стиле Twitter.

Соответственно переделать DetailView

    **Теперь при GET-запросе вид страницы зависит от того голосовал или нет пользователь
    при AJAX POST-запросе возвращается в ответ блок HTML с результатами голосования, который можно подменить на странице.
    ResultView больше не нужна.

По jQuery смотреть $.post, $().serialize, $().replaceWith
**

**Comment by vkuryachenko** [comment]
Больше на странице голосования нет кнопки "Отправить",
теперь голосование происходит при нажатии на вариант ответов.
после нажатия на вариант показываются результаты голосования
Соответственно переделать DetailView

```
Теперь при GET-запросе вид страницы зависит от того голосовал или нет пользователь
при AJAX POST-запросе возвращается в ответ блок HTML с результатами голосования, который можно подменить на странице.
ResultView больше не нужна.
```

По jQuery смотреть $.post, $().serialize, $().replaceWith
