### ISSUE TITLE
Когда картинка не загружена для вопроса

### ISSUE THREAD

**Issue by akuryachenko** [vkuryachenko/mysite#24]
Вставляется картинка с путем на /static/,
которой естественно нет.

**Comment by vkuryachenko** [comment]
index.html 
{% if question.question_img %}<img src="/static/{{ question.question_img}}" alt="" class="circle">{% endif %}

detail.html results.html

{% if question.question_img %}<img src="/static/{{ question.question_img}}">{% endif %}
