### ISSUE TITLE
test_detail_view_with_a_future_question проходится с ошибкой

### ISSUE THREAD

**Issue by akuryachenko** [vkuryachenko/mysite#5]
Нет проверки на доступ к вопросу с датой публикации в будущем

**Comment by akuryachenko** [comment]
Хоть список вопросов и фильтруется на предмет даты публикации, но у вьюшки для просмотра  вопроса нет проверки

**Comment by vkuryachenko** [comment]
class DetailView(generic.UpdateView):
.
.
.  
    def get_queryset(self):
        qs = super(DetailView, self).get_queryset()
        return qs.filter(pub_date__lte=timezone.now())

python manage.py test polls
Creating test database for alias 'default'...

## ..........

Ran 10 tests in 0.027s

OK
Destroying test database for alias 'default'...
