### ISSUE TITLE
Material design с пом http://materializecss.com

### ISSUE THREAD

**Issue by akuryachenko** [vkuryachenko/mysite#9]
Итак, предлагаю начать доп. задания с верстки шаблона. Оно и более красивее и более завершенным выглядеть будет, да и другие фичи уже будем встраивать по месту в текущую верстку.

Начать стоит с http://materializecss.com/getting-started.html
Можно взять готовый "Starter Template", убрать все ненужное и встроить туда список вопросов.
(Только у футера оранжевый цвет убрать, а то мне глазам от такого больно.)

Сейчас шаблоны не наследуются. Я это не стал выносить в отдельный тикет, т.к. переделывать в любом случае нужно будет.

Обычно делают base.html c <html>, <body>, <head> и в него включают блоки {% block content %}{% endblock %}
А их переопределяют в наследуемых шаблонах.

И тогда у на общий вид страницы выглядит одинаково - логотип, шапка, футер, а контент каждая наследуемая страница переопределяет контентную часть.

**Comment by akuryachenko** [comment]
Еще список вопросов бы перенести с /polls/ в /

**Comment by vkuryachenko** [comment]
urlpatterns = [
    url(r'^$', vw.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', vw.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', vw.ResultsView.as_view(), name='results'),
    url(r'^admin/', admin.site.urls),
]
